- name: Install ArgoCD
  hosts: all
  become: true

  tasks:
    - name: Create ArgoCD namespace
      shell: |
        kubectl create namespace argocd 

    - name: Install ArgoCD
      shell: |
        kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml