- name: Create Docker Registry Secret
  hosts: all
  become: true

  tasks:
    - name: Debug variables
      debug:
        msg: "Available variables: {{ vars }}"
        
    - name: Create Docker Registry Secret
      shell: |
        kubectl create secret docker-registry {{ docker_secret_name }} \
        --docker-server={{ docker_registry_server }} \
        --docker-username={{ docker_registry_username }} \
        --docker-password={{ docker_registry_password }} \
        --docker-email={{ docker_registry_email }}