- name: Create Docker Registry Secret
  hosts: all
  become: true

  tasks:
    - name: Create Docker Registry Secret
      shell: |
        kubectl create secret generic {{ env_secret_name }} --from-env-file={{ env_secret_file }}