- name: Create Argo CD Repository Secret
  hosts: all
  become: true

  tasks:
    - name: Create Argo CD Repository Secret
      shell: |
        kubectl create secret generic {{ repo_secret_name }} \
          --namespace={{ namespace }} \
          --from-literal=type=git \
          --from-literal=url={{ repo_url }} \
          --from-literal=username={{ repo_username }} \
          --from-literal=password={{ repo_token }}

    - name: Label Argo CD Repository Secret
      shell: |
        kubectl label secret {{ repo_secret_name }} \
          --namespace={{ namespace }} \
          argocd.argoproj.io/secret-type=repository 